"""
views/content_player.py
────────────────────────
Content reader: sidebar navigation + Markdown lesson viewer.

Hybrid features added:
  - Tabs: "📖 Lesson Content" | "⚡ Quick Chat (Llama)" | "🎙️ Audio Script"
  - "🎙️ Generate Audio Script" optional button (Llama 3.2).
  - Course badge showing refinement status ("✨ Refined by Gemini").

State keys used:
  active_course_id     : int — set by home.py before navigating here
  player_lesson_id     : int — the currently selected Lesson ID
  quick_chat_{id}      : QuickChatService instance cached per lesson
"""

from __future__ import annotations

import streamlit as st

from repositories import course_repo
from repositories.quiz_repo import has_quiz


def _get_quick_chat_service(lesson_id: int):
    """Return (or create and cache) a QuickChatService for the given lesson."""
    from services.chatbot_service import QuickChatService
    key = f"quick_chat_{lesson_id}"
    if key not in st.session_state:
        st.session_state[key] = QuickChatService(lesson_id)
    return st.session_state[key]


def render() -> None:
    """
    Render the content player.

    Called by `app.py` when `st.session_state["page"] == "player"`.
    """
    course_id: int | None = st.session_state.get("active_course_id")
    if not course_id:
        st.error("No course selected. Go back to Home.")
        if st.button("🏠 Home"):
            st.session_state["page"] = "home"
            st.rerun()
        return

    course = course_repo.get_course(course_id)
    if not course:
        st.error("Course not found.")
        return

    # ── Sidebar: module/lesson navigation ─────────────────────────────────────
    with st.sidebar:
        st.markdown(f"### 📚 {course.title}")

        # Refinement badge
        if getattr(course, "refined", False):
            st.markdown(
                "<span style='background:#dcfce7;color:#166534;padding:2px 8px;"
                "border-radius:4px;font-size:0.75rem'>✅ Refined</span>",
                unsafe_allow_html=True,
            )

        st.markdown("---")

        for module in course.modules:
            st.markdown(f"**{module.title}**")
            for lesson in sorted(module.lessons, key=lambda l: l.order_index):
                is_active = st.session_state.get("player_lesson_id") == lesson.id
                label = f"{'▶ ' if is_active else '  '}{lesson.title}"
                if st.button(label, key=f"nav_lesson_{lesson.id}", use_container_width=True):
                    st.session_state["player_lesson_id"] = lesson.id
                    st.rerun()

        st.markdown("---")
        if st.button("🏠 Back to Home", use_container_width=True):
            st.session_state["page"] = "home"
            st.rerun()

    # ── Main area: lesson content ──────────────────────────────────────────────
    lesson_id: int | None = st.session_state.get("player_lesson_id")

    if not lesson_id:
        # Default: auto-select first lesson
        if course.modules and course.modules[0].lessons:
            first_lesson = sorted(
                course.modules[0].lessons, key=lambda l: l.order_index
            )[0]
            st.session_state["player_lesson_id"] = first_lesson.id
            st.rerun()
        else:
            st.info("No lessons available yet.")
            return

    lesson = course_repo.get_lesson(lesson_id)
    if not lesson:
        st.error("Lesson not found.")
        return

    # ── Tabs: Lesson | Quick Chat | Audio Script ───────────────────────────────
    tab_content, tab_chat, tab_audio = st.tabs([
        "📖 Lesson Content",
        "⚡ Quick Chat (Llama)",
        "🎙️ Audio Script",
    ])

    # ── Tab 1: Lesson Content ──────────────────────────────────────────────────
    with tab_content:
        # Model badge
        st.markdown(
            "<div style='margin-bottom:0.5rem'>"
            "<span style='background:#f3f4f6;color:#374151;padding:2px 8px;"
            "border-radius:4px;font-size:0.75rem;border:1px solid #e5e7eb'>"
            "⚡ Generated by Llama 3.2</span>"
            + (
                "<span style='background:#dcfce7;color:#166534;padding:2px 8px;"
                "border-radius:4px;font-size:0.75rem;border:1px solid #bbf7d0;margin-left:6px'>"
                "✅ Refined</span>"
                if getattr(course, "refined", False)
                else ""
            )
            + "</div>",
            unsafe_allow_html=True,
        )

        st.markdown(lesson.content_markdown or "_No content generated for this lesson yet._")

        # ── Footer actions ─────────────────────────────────────────────────────
        st.markdown("---")
        col1, col2, col3 = st.columns(3)
        with col1:
            if has_quiz(course_id):
                if st.button("📝 Take Quiz", use_container_width=True, key="player_quiz_btn"):
                    st.session_state["page"] = "quiz"
                    st.rerun()
        with col2:
            if st.button("🧠 AI Tutor (Gemini)", use_container_width=True, key="player_tutor_btn"):
                st.session_state["page"] = "chatbot"
                st.rerun()
        with col3:
            st.markdown(
                f"<small style='color:#9ca3af'>Course: {course.title}</small>",
                unsafe_allow_html=True,
            )

    # ── Tab 2: Quick Chat (Llama 3.2) ─────────────────────────────────────────
    with tab_chat:
        st.markdown(
            "<p style='color:#6b7280;font-size:0.875rem'>"
            "⚡ <strong>Powered by Llama 3.2</strong> — Fast answers about <em>this lesson only</em>. "
            "For cross-module questions, use the 🧠 AI Tutor tab.</p>",
            unsafe_allow_html=True,
        )

        try:
            qc_service = _get_quick_chat_service(lesson_id)
        except Exception as e:
            st.error(f"Failed to load Quick Chat: {e}")
            st.stop()

        col_title, col_clear = st.columns([4, 1])
        with col_clear:
            if st.button("🗑️ Clear", key=f"qc_clear_{lesson_id}", use_container_width=True):
                qc_service.clear_history()
                st.session_state.pop(f"quick_chat_{lesson_id}", None)
                st.rerun()

        # Display history
        qc_history = qc_service.get_history()

        if not qc_history:
            with st.chat_message("assistant"):
                st.markdown(
                    f"Hi! I'm here to help with **{lesson.title}**. "
                    "Ask me any quick question about this lesson!"
                )

        for msg in qc_history:
            with st.chat_message(msg.role):
                st.markdown(msg.content)

        # Quick chat input
        if qc_prompt := st.chat_input(
            "Ask a quick question about this lesson...",
            key=f"qc_input_{lesson_id}",
        ):
            with st.chat_message("user"):
                st.markdown(qc_prompt)
            with st.chat_message("assistant"):
                with st.spinner("⚡ Llama is thinking..."):
                    qc_reply = qc_service.chat(qc_prompt)
                st.markdown(qc_reply)

    # ── Tab 3: Audio Script ────────────────────────────────────────────────────
    with tab_audio:
        st.markdown(
            "<p style='color:#6b7280;font-size:0.875rem'>"
            "⚡ <strong>Powered by Llama 3.2</strong> — "
            "Narration script for audio/video production or text-to-speech.</p>",
            unsafe_allow_html=True,
        )

        has_script = bool(getattr(lesson, "audio_script", ""))

        if has_script:
            st.markdown("#### 🎙️ Narration Script")
            st.text_area(
                "Script (plain text, ready for TTS or recording)",
                value=lesson.audio_script,
                height=400,
                key=f"audio_script_display_{lesson_id}",
                help="Copy this text to use with a TTS system or voice recording tool.",
            )

            col_regen, _ = st.columns([1, 3])
            with col_regen:
                if st.button(
                    "🔄 Regenerate Script",
                    key=f"regen_script_{lesson_id}",
                    use_container_width=True,
                ):
                    with st.spinner("⚡ Llama is writing your script..."):
                        try:
                            from services.content_service import generate_audio_script
                            script = generate_audio_script(lesson_id)
                            st.success("Script regenerated!")
                            st.rerun()
                        except Exception as e:
                            st.error(f"Script generation failed: {e}")
        else:
            st.info("No audio script generated yet for this lesson.")

            if st.button(
                "🎙️ Generate Audio Script",
                type="primary",
                key=f"gen_script_{lesson_id}",
                disabled=not lesson.content_markdown,
                help="Generates a narration script from the lesson content using Llama 3.2.",
            ):
                with st.spinner("⚡ Llama is writing your narration script..."):
                    try:
                        from services.content_service import generate_audio_script
                        script = generate_audio_script(lesson_id)
                        st.success("✅ Script generated!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"Script generation failed: {e}")

            if not lesson.content_markdown:
                st.caption("⚠️ Generate lesson content first before creating a script.")
