"""
db/database.py
──────────────
Database engine setup, session management, and schema initialisation.

Why SQLAlchemy 2.0 style?
  - `mapped_column` + `Mapped[T]` give full type-inference in IDEs.
  - `sessionmaker` + context manager pattern prevents session leaks.
  - `create_engine` with `check_same_thread=False` is required for SQLite
    when used with Streamlit, which may access the DB from multiple threads.
"""

from contextlib import contextmanager
from typing import Generator

from sqlalchemy import create_engine, event
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session, sessionmaker

import config
from db.models import Base


# ── Engine ────────────────────────────────────────────────────────────────────

engine = create_engine(
    config.DB_URL,
    connect_args={"check_same_thread": False},  # Needed for SQLite + Streamlit
    echo=False,          # Set True during development to log all SQL statements
)


# ── Enable WAL mode for SQLite ────────────────────────────────────────────────
# WAL (Write-Ahead Logging) allows concurrent reads while a write is in progress.
# This matters for Streamlit where multiple reruns can overlap.

@event.listens_for(engine, "connect")
def _set_sqlite_pragma(dbapi_conn, _connection_record) -> None:
    """
    Called once per new SQLite connection.
    Sets WAL journal mode and enables foreign key enforcement
    (SQLite disables FK checks by default).
    """
    cursor = dbapi_conn.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()


# ── Session Factory ───────────────────────────────────────────────────────────

_SessionLocal = sessionmaker(
    bind=engine,
    autocommit=False,   # Explicit commits required — safer for error handling
    autoflush=False,    # Manual flush gives control over when SQL is emitted
    expire_on_commit=False,  # Avoid lazy-load errors after commit in Streamlit
)


@contextmanager
def get_session() -> Generator[Session, None, None]:
    """
    Provide a transactional database session to callers.

    Usage
    -----
    >>> with get_session() as db:
    ...     course = db.get(Course, 1)

    Guarantees
    ----------
    - Commits only on clean exit.
    - Rolls back automatically on any exception.
    - Always closes the session to return the connection to the pool.
    """
    session: Session = _SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


# ── Schema Initialisation ─────────────────────────────────────────────────────

def init_db() -> None:
    """
    Create all tables defined in `db/models.py` if they do not already exist.

    This is idempotent: calling it multiple times is safe.
    Called once at Streamlit app startup in `app.py`.

    Also runs `_migrate_schema()` to safely add new columns to existing
    databases without data loss (via ALTER TABLE with try/except).
    """
    Base.metadata.create_all(bind=engine)
    _migrate_schema()


def _migrate_schema() -> None:
    """
    Apply non-destructive ALTER TABLE migrations for new columns.

    Each statement is wrapped in try/except so running against a DB that
    already has the column is a no-op (SQLite raises OperationalError on
    duplicate columns). Safe to call on every startup.
    """
    migrations = [
        # Lesson — audio script generated by Llama
        "ALTER TABLE lessons ADD COLUMN audio_script TEXT NOT NULL DEFAULT ''",
        # Course — multimodal source document extracted by Gemini
        "ALTER TABLE courses ADD COLUMN source_document TEXT NOT NULL DEFAULT ''",
        # Course — flag set after Gemini refinement pass
        "ALTER TABLE courses ADD COLUMN refined BOOLEAN NOT NULL DEFAULT 0",
    ]
    with engine.connect() as conn:
        for sql in migrations:
            try:
                conn.execute(__import__("sqlalchemy").text(sql))
                conn.commit()
            except Exception:
                # Column already exists — safe to ignore
                conn.rollback()
